
name: FaceAuth
main: EnterTainerSK\FaceLogin
api: [2.0.0, 3.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA10]
version: 1.0.0
author: EnterTainerSK
permissions:
  facelogin.show:
    default: true
    description: Shows player their skin's face on joining.
